DOMAIN = "samsung_find"

CONF_REFRESH_TOKEN = "refresh_token"
CONF_ACCESS_TOKEN = "access_token"
CONF_CLIENT_ID = "client_id"
CONF_USER_ID = "user_id"
CONF_LAST_TOKEN_REFRESH = "last_token_refresh"
CONF_TOKEN_EXPIRES_IN = "token_expires_in"
CONF_HEADERS = "headers"
CONF_COUNTRY_CODE = "country_code"

CONF_ACTIVE_SMARTTAGS = "active_smarttags"
CONF_ACTIVE_OTHERS = "active_others"
CONF_IGNORE_MOBILE_DEVICES = "ignore_mobile_devices"

CONF_ACTIVE_SMARTTAGS_DEFAULT = True
CONF_ACTIVE_OTHER_DEFAULT = True
CONF_IGNORE_MOBILE_DEVICES_DEFAULT = True

CONF_UPDATE_INTERVAL = "update_interval"
CONF_UPDATE_INTERVAL_DEFAULT = 300

CONF_OAUTH2_TOKEN_URL = "auth_server_url"
CONF_USERAUTH_TOKEN = "userauth_token"

MOBILE_DEVICE_TYPES = {"PHONE", "TABLET", "WATCH", "BUDS"}

BATTERY_LEVELS = {"FULL": 100, "MEDIUM": 50, "LOW": 15, "VERY_LOW": 5}
